"""SHA256 provenance audit for integrated layers.

Two layers carry verbatim content from upstream bundles and must be
tracked via content-hash audit rather than unit tests:

- **Layer 05** (Advanced Orchestration) — 26 orchestration modules with
  the original prompt body inside a triple-backtick fenced block.
- **Layer 06** (ECA Cognitive Engine) — 34 content files with the
  original body inside a quadruple-backtick fenced block and the hash
  of the original source already recorded in frontmatter as
  ``source_sha256``.

Why body-only: the YAML frontmatter is prompt-x-lab native and may
evolve (version bumps, validated flags). The body is the provenance-
critical part — any change there is a content edit and must be visible
to a reviewer.

Run::

    python -m pxl.audit write [layer]   # writes <layer>/AUDIT.sha256
    python -m pxl.audit verify [layer]  # non-zero if any body changed

``layer`` defaults to ``all`` — write/verify both layers.
"""

from __future__ import annotations

import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass(slots=True, frozen=True)
class LayerSpec:
    dir: Path
    audit_file: Path
    fence_re: re.Pattern[str]
    label: str


LAYER_CONFIG: dict[str, LayerSpec] = {
    "05": LayerSpec(
        dir=REPO_ROOT / "05_orchestration",
        audit_file=REPO_ROOT / "05_orchestration" / "AUDIT.sha256",
        fence_re=re.compile(r"```\n(.*?)\n```", re.DOTALL),
        label="layer 05 (Advanced Orchestration)",
    ),
    "06": LayerSpec(
        dir=REPO_ROOT / "06_eca_engine",
        audit_file=REPO_ROOT / "06_eca_engine" / "AUDIT.sha256",
        fence_re=re.compile(r"````(?:\w+)?\n(.*?)\n````", re.DOTALL),
        label="layer 06 (ECA Cognitive Engine)",
    ),
    "07": LayerSpec(
        dir=REPO_ROOT / "07_kriterion",
        audit_file=REPO_ROOT / "07_kriterion" / "AUDIT.sha256",
        fence_re=re.compile(r"````(?:\w+)?\n(.*?)\n````", re.DOTALL),
        label="layer 07 (Kriterion)",
    ),
}

# Backwards-compat names used by existing tests.
LAYER_DIR = LAYER_CONFIG["05"].dir
AUDIT_FILE = LAYER_CONFIG["05"].audit_file
BODY_RE = LAYER_CONFIG["05"].fence_re


def extract_body(text: str, fence_re: re.Pattern[str] | None = None) -> str:
    """Return the first fenced code block body, or ``""`` if none."""

    pattern = fence_re if fence_re is not None else BODY_RE
    m = pattern.search(text)
    return m.group(1) if m else ""


def hash_body(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def iter_orchestration_files() -> list[Path]:
    """Backwards-compat: layer-05 file iterator used by existing tests."""

    return _iter_layer_files(LAYER_CONFIG["05"])


def _iter_layer_files(cfg: LayerSpec) -> list[Path]:
    return sorted(p for p in cfg.dir.rglob("*.md") if p.name.upper() != "README.MD")


def _compute_layer_manifest(cfg: LayerSpec) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for path in _iter_layer_files(cfg):
        text = path.read_text(encoding="utf-8")
        body = extract_body(text, fence_re=cfg.fence_re)
        digest = hash_body(body)
        rel = path.relative_to(REPO_ROOT).as_posix()
        out.append((rel, digest))
    return sorted(out)


def compute_manifest() -> list[tuple[str, str]]:
    """Backwards-compat: layer-05 manifest used by existing tests."""

    return _compute_layer_manifest(LAYER_CONFIG["05"])


def render_manifest(entries: list[tuple[str, str]], label: str = "layer 05") -> str:
    header = (
        f"# prompt-x-lab · {label} · SHA256 body audit\n"
        "# Format: <sha256>  <path>\n"
        "# Generated by pxl.audit; do not edit by hand.\n"
        "# Run `python -m pxl.audit verify` to check integrity.\n\n"
    )
    lines = [f"{digest}  {path}" for path, digest in entries]
    return header + "\n".join(lines) + "\n"


def _write_layer(cfg: LayerSpec) -> int:
    manifest = _compute_layer_manifest(cfg)
    cfg.audit_file.parent.mkdir(parents=True, exist_ok=True)
    cfg.audit_file.write_text(render_manifest(manifest, label=cfg.label), encoding="utf-8")
    print(f"wrote {cfg.audit_file.relative_to(REPO_ROOT)} ({len(manifest)} entries)")
    return 0


def _verify_layer(cfg: LayerSpec) -> int:
    audit_file = cfg.audit_file
    label = cfg.label
    if not audit_file.exists():
        print(f"FAIL: audit file missing: {audit_file}", file=sys.stderr)
        return 2
    expected: dict[str, str] = {}
    for line in audit_file.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        digest, _, path = line.partition("  ")
        if digest and path:
            expected[path] = digest.strip()

    actual = dict(_compute_layer_manifest(cfg))
    missing = sorted(set(expected) - set(actual))
    extra = sorted(set(actual) - set(expected))
    changed = sorted(p for p in expected if p in actual and expected[p] != actual[p])

    if not missing and not extra and not changed:
        print(f"OK: {label} audit clean ({len(actual)} files)")
        return 0

    for p in missing:
        print(f"MISSING: {p}", file=sys.stderr)
    for p in extra:
        print(f"EXTRA:   {p}", file=sys.stderr)
    for p in changed:
        print(f"CHANGED: {p}  expected={expected[p]}  actual={actual[p]}", file=sys.stderr)
    return 1


def write_manifest(layer: str = "all") -> int:
    rc = 0
    if layer in ("all", "05"):
        rc |= _write_layer(LAYER_CONFIG["05"])
    if layer in ("all", "06"):
        rc |= _write_layer(LAYER_CONFIG["06"])
    if layer in ("all", "07"):
        rc |= _write_layer(LAYER_CONFIG["07"])
    return rc


def verify_manifest(layer: str = "all") -> int:
    rc = 0
    if layer in ("all", "05"):
        rc |= _verify_layer(LAYER_CONFIG["05"])
    if layer in ("all", "06"):
        rc |= _verify_layer(LAYER_CONFIG["06"])
    if layer in ("all", "07"):
        rc |= _verify_layer(LAYER_CONFIG["07"])
    return rc


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    cmd = args[0] if args else "verify"
    layer = args[1] if len(args) > 1 else "all"
    if layer not in ("all", "05", "06", "07"):
        print(f"unknown layer: {layer}", file=sys.stderr)
        return 2
    if cmd == "write":
        return write_manifest(layer)
    if cmd == "verify":
        return verify_manifest(layer)
    print(f"unknown command: {cmd}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
