"""SHA256 audit of Layer 05 (Advanced Orchestration) — provenance chain.

Layer 05 is an integrated verbatim copy of a third-party bundle. This
module computes a SHA256 of each orchestration file's body (the content
between the opening ```` ``` ```` fence and the closing ```` ``` ```` fence)
and writes a deterministic audit manifest.

Why body-only: the YAML frontmatter is prompt-x-lab native and may
evolve (version bumps, validated flags). The body is the provenance-
critical part — any change there is a content edit and must be visible
to a reviewer.

Run::

    python -m pxl.audit write   # writes 05_orchestration/AUDIT.sha256
    python -m pxl.audit verify  # exits non-zero if any body changed
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
LAYER_DIR = REPO_ROOT / "05_orchestration"
AUDIT_FILE = LAYER_DIR / "AUDIT.sha256"

BODY_RE = re.compile(r"```\n(.*?)\n```", re.DOTALL)


def extract_body(text: str) -> str:
    """Return the first fenced code block body, or ``""`` if none."""

    m = BODY_RE.search(text)
    return m.group(1) if m else ""


def hash_body(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def iter_orchestration_files() -> list[Path]:
    return sorted(p for p in LAYER_DIR.rglob("*.md") if p.name.upper() != "README.MD")


def compute_manifest() -> list[tuple[str, str]]:
    """Return sorted [(relative_path, sha256)] for every orchestration file."""

    out: list[tuple[str, str]] = []
    for path in iter_orchestration_files():
        text = path.read_text(encoding="utf-8")
        body = extract_body(text)
        digest = hash_body(body)
        rel = path.relative_to(REPO_ROOT).as_posix()
        out.append((rel, digest))
    return sorted(out)


def render_manifest(entries: list[tuple[str, str]]) -> str:
    header = (
        "# prompt-x-lab · layer 05 · SHA256 body audit\n"
        "# Format: <sha256>  <path>\n"
        "# Generated by pxl.audit; do not edit by hand.\n"
        "# Run `python -m pxl.audit verify` to check integrity.\n\n"
    )
    lines = [f"{digest}  {path}" for path, digest in entries]
    return header + "\n".join(lines) + "\n"


def write_manifest() -> int:
    manifest = compute_manifest()
    AUDIT_FILE.write_text(render_manifest(manifest), encoding="utf-8")
    print(f"wrote {AUDIT_FILE.relative_to(REPO_ROOT)} ({len(manifest)} entries)")
    return 0


def verify_manifest() -> int:
    if not AUDIT_FILE.exists():
        print(f"FAIL: audit file missing: {AUDIT_FILE}", file=sys.stderr)
        return 2
    expected: dict[str, str] = {}
    for line in AUDIT_FILE.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        digest, _, path = line.partition("  ")
        if digest and path:
            expected[path] = digest.strip()

    actual = dict(compute_manifest())
    missing = sorted(set(expected) - set(actual))
    extra = sorted(set(actual) - set(expected))
    changed = sorted(p for p in expected if p in actual and expected[p] != actual[p])

    if not missing and not extra and not changed:
        print(f"OK: layer 05 audit clean ({len(actual)} files)")
        return 0

    for p in missing:
        print(f"MISSING: {p}", file=sys.stderr)
    for p in extra:
        print(f"EXTRA:   {p}", file=sys.stderr)
    for p in changed:
        print(f"CHANGED: {p}  expected={expected[p]}  actual={actual[p]}", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    cmd = args[0] if args else "verify"
    if cmd == "write":
        return write_manifest()
    if cmd == "verify":
        return verify_manifest()
    print(f"unknown command: {cmd}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
